version: '3.8'

services:
  my-go-app:
    image: fx-getter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV_VAR=some_value
